(() => {
  'use strict';
  if(!window.MomoAdmin||!window.MomoAdminActivity)return;
  const $=id=>document.getElementById(id), esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  let page=1, rows=[], currentDrawer=null;
  const typeOf=log=>String(log.entityType||'SYSTEM').toUpperCase();
  const important=log=>/(DELETE|REMOVE|REVOKE|DEACTIVATE|SETTING|삭제|비활성|회수|운영 설정)/i.test(`${log.action||''} ${log.description||''} ${typeOf(log)}`);
  const dateValue=value=>{const date=new Date(value);return Number.isNaN(date.getTime())?null:date};
  const formatDate=value=>{const date=dateValue(value);return date?new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(date):'-'};
  const category=type=>({ORDER:'주문',MENU:'메뉴',MEMBER:'회원',QNA:'문의',POINT:'포인트',COUPON:'쿠폰',REWARD:'리워드',SETTING:'설정',NOTICE:'공지',CUSTOMER:'고객'}[type]||'시스템');
  function allLogs(){const logs=MomoAdminActivity.getLogs();return Array.isArray(logs)?logs:[]}
  function renderStats(logs){const today=new Date().toDateString(),count=type=>logs.filter(log=>typeOf(log)===type).length;const cards=[['◷','오늘 활동',logs.filter(log=>dateValue(log.createdAt)?.toDateString()===today).length,'오늘 기록된 작업'],['□','주문 관련',count('ORDER'),'주문 상태와 메모'],['◇','메뉴 관련',count('MENU'),'판매 및 품절 변경'],['○','회원 관련',count('MEMBER'),'회원 정보 변경'],['☆','리워드 관련',logs.filter(log=>['POINT','COUPON','REWARD'].includes(typeOf(log))).length,'포인트와 쿠폰'],['⌘','운영 설정',count('SETTING'),'운영 정책 변경']];$('activityStats').innerHTML=cards.map(([icon,label,value,desc])=>`<article><i aria-hidden="true">${icon}</i><div><small>${label}</small><strong>${value.toLocaleString()}건</strong><span>${desc}</span></div></article>`).join('')}
  function filtered(logs){const term=$('activitySearch').value.trim().toLowerCase(),period=$('activityPeriod').value,admin=$('adminFilter').value,type=$('actionFilter').value,level=$('importanceFilter').value,now=Date.now();return logs.filter(log=>{const date=dateValue(log.createdAt),isImportant=important(log);return(!type||typeOf(log)===type)&&(!admin||String(log.adminId??log.adminName)===admin)&&(!level||(level==='important')===isImportant)&&(!term||`${log.adminName||''} ${log.entityId||''} ${log.description||''} ${log.action||''}`.toLowerCase().includes(term))&&(period==='all'||(period==='today'?date?.toDateString()===new Date().toDateString():date&&date.getTime()>=now-Number(period)*86400000))}).sort((a,b)=>(dateValue(b.createdAt)?.getTime()||0)-(dateValue(a.createdAt)?.getTime()||0))}
  function render(){const logs=allLogs();renderStats(logs);rows=filtered(logs);const size=Number($('activityPageSize').value),pages=Math.max(1,Math.ceil(rows.length/size));page=Math.min(page,pages);const visible=rows.slice((page-1)*size,page*size);$('activityCount').textContent=`검색 결과 ${rows.length.toLocaleString()}건`;$('activityTotal').textContent=`전체 ${logs.length.toLocaleString()}건`;$('activityUpdated').textContent=new Date().toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'});$('activityList').innerHTML=visible.length?visible.map((log,index)=>{const type=typeOf(log),critical=important(log);return`<article class="activity-row ${critical?'is-important':''}" data-index="${(page-1)*size+index}"><span class="activity-tag type-${type}">${category(type)}</span><div class="activity-copy"><strong>${esc(log.adminName||'MOMO 관리자')}</strong><p>${esc(log.description||log.action||'운영 작업')}</p></div><small class="activity-entity">${esc(log.entityId!=null?`${category(type)} · ${log.entityId}`:'관련 데이터 없음')}</small><time>${formatDate(log.createdAt)}</time><button type="button" data-detail aria-label="활동 로그 상세 보기">···</button></article>`}).join(''):'<div class="activity-empty"><strong>조건에 맞는 활동 로그가 없습니다.</strong><p>검색어나 필터를 변경해 다시 확인해 주세요.</p></div>';$('activityPagination').innerHTML=Array.from({length:pages},(_,index)=>`<button type="button" data-page="${index+1}" ${page===index+1?'aria-current="page"':''}>${index+1}</button>`).join('')}
  function showDrawer(log,trigger){currentDrawer=trigger;const detail=[['작업 유형',category(typeOf(log))],['관리자',log.adminName||'MOMO 관리자'],['대상 ID',log.entityId??'-'],['작업 내용',log.description||log.action||'-'],['작업 사유',log.reason||log.memo||'기록되지 않음'],['시간',formatDate(log.createdAt)],['IP',log.ip||'기록되지 않음'],['브라우저',log.browser||log.userAgent||'기록되지 않음']];$('activityDrawerContent').innerHTML=`<dl class="audit-detail">${detail.map(([key,value])=>`<div><dt>${key}</dt><dd>${esc(value)}</dd></div>`).join('')}</dl><section class="change-data"><h3>작업 전 데이터</h3><pre>${esc(JSON.stringify(log.before??{},null,2))}</pre><h3>작업 후 데이터</h3><pre>${esc(JSON.stringify(log.after??{},null,2))}</pre></section>`;const drawer=$('activityDrawer');drawer.classList.add('is-open');drawer.setAttribute('aria-hidden','false');drawer.querySelector('[data-close-drawer]').focus()}
  function closeDrawer(){const drawer=$('activityDrawer');drawer.classList.remove('is-open');drawer.setAttribute('aria-hidden','true');currentDrawer?.focus();currentDrawer=null}
  function exportCsv(){const cells=value=>`"${String(value??'').replace(/"/g,'""')}"`,csv=['유형,관리자,작업 내용,관련 ID,일시',...rows.map(log=>[typeOf(log),log.adminName,log.description,log.entityId,formatDate(log.createdAt)].map(cells).join(','))].join('\r\n'),blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`momo-admin-audit-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(link.href)}
  function populateAdmins(){const map=new Map();allLogs().forEach(log=>map.set(String(log.adminId??log.adminName),log.adminName||'MOMO 관리자'));$('adminFilter').innerHTML='<option value="">전체 관리자</option>'+[...map].map(([value,label])=>`<option value="${esc(value)}">${esc(label)}</option>`).join('')}
  ['actionFilter','activityPeriod','adminFilter','importanceFilter','activitySearch','activityPageSize'].forEach(id=>$(id).addEventListener(id==='activitySearch'?'input':'change',()=>{page=1;render()}));
  $('activityReset').onclick=()=>{['actionFilter','adminFilter','importanceFilter'].forEach(id=>$(id).value='');$('activityPeriod').value='all';$('activitySearch').value='';page=1;render()};$('activityExport').onclick=exportCsv;$('activityRefresh').onclick=()=>{populateAdmins();render()};$('activityPagination').onclick=event=>{const button=event.target.closest('[data-page]');if(button){page=Number(button.dataset.page);render()}};$('activityList').onclick=event=>{const button=event.target.closest('[data-detail]');if(!button)return;const row=button.closest('[data-index]');showDrawer(rows[Number(row.dataset.index)],button)};document.querySelectorAll('[data-close-drawer]').forEach(button=>button.onclick=closeDrawer);document.addEventListener('keydown',event=>{if(event.key==='Escape')closeDrawer()});window.addEventListener('storage',()=>{populateAdmins();render()});$('activityToday').textContent=new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long',day:'numeric',weekday:'short'}).format(new Date());populateAdmins();render();
})();
