(() => {
  const KEY = 'momoInquiries';
  const categories = { MENU:'메뉴', ORDER:'주문', PAYMENT:'결제', COUPON:'쿠폰', MEMBERSHIP:'멤버십', STORE:'매장', ETC:'기타' };
  const read = () => { try { const value=JSON.parse(localStorage.getItem(KEY)||'[]'); return Array.isArray(value)?value:[]; } catch { return []; } };
  const normalize = (item) => ({ ...item, isPrivate:item?.isPrivate===true||item?.isPrivate===1||String(item?.isPrivate).toLowerCase()==='true', answerHistory:Array.isArray(item.answerHistory)?item.answerHistory:[], adminMemo:String(item.adminMemo||'') });
  const save = (items) => { if(!Array.isArray(items)) throw new Error('문의 데이터가 올바르지 않습니다.'); localStorage.setItem(KEY,JSON.stringify(items.map(normalize))); return items; };
  const notify = (item, message) => { const key='momoNotifications'; let list=[]; try{list=JSON.parse(localStorage.getItem(key)||'[]')}catch{} if(!Array.isArray(list))list=[]; list.unshift({id:id(),userId:item.userId,userEmail:item.userEmail,type:'QNA_ANSWER',message,inquiryId:item.id,createdAt:new Date().toISOString(),read:false}); localStorage.setItem(key,JSON.stringify(list)); };
  const id = () => `QNA-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`.toUpperCase();
  const admin = (u) => u?.role === 'ADMIN';
  const identity = (value) => String(value??'').trim().toLowerCase();
  const sameUser = (a,b) => Boolean(identity(a)) && identity(a) === identity(b);
  const owns = (item,user) => { if(!item||!user)return false; if(typeof user!=='object')return sameUser(item.userId,user)||sameUser(item.userEmail,user); return [user.id,user.email].some(value=>sameUser(item.userId,value)||sameUser(item.userEmail,value)); };
  const validate = (p) => { if(!categories[p.category]) throw new Error('문의 유형을 선택해주세요.'); const title=String(p.title||'').trim(),content=String(p.content||'').trim(); if(!title||title.length>100) throw new Error('제목은 1자 이상 100자 이하로 입력해주세요.'); if(content.length<10||content.length>2000) throw new Error('내용은 10자 이상 2,000자 이하로 입력해주세요.'); return {...p,title,content,isPrivate:Boolean(p.isPrivate)}; };
  const api = {
    categories, getInquiries:()=>read().map(normalize), saveInquiries:save, generateInquiryId:id, isAdmin:admin,
    getInquiryById(qid){const found=read().find(x=>String(x.id)===String(qid));return found?normalize(found):null},
    getMyInquiries(user){return read().map(normalize).filter(item=>owns(item,user))},
    createInquiry(payload,user){if(!user)throw new Error('로그인이 필요합니다.'); const p=validate(payload),now=new Date().toISOString(); const item={id:id(),userId:user.id??user.email,userEmail:user.email||'',userName:user.name||'',category:p.category,title:p.title,content:p.content,isPrivate:p.isPrivate,status:'PENDING',createdAt:now,updatedAt:null,answer:null}; const all=read();all.push(item);save(all);return item},
    updateInquiry(qid,user,payload){const all=read(),item=all.find(x=>String(x.id)===String(qid));if(!item||!owns(item,user)||item.status!=='PENDING')throw new Error('수정 권한이 없습니다.');Object.assign(item,validate(payload),{updatedAt:new Date().toISOString()});save(all);return normalize(item)},
    deleteInquiry(qid,user){const all=read(),i=all.findIndex(x=>String(x.id)===String(qid));if(i<0||!owns(all[i],user)||all[i].status!=='PENDING')throw new Error('삭제 권한이 없습니다.');all.splice(i,1);save(all);return true},
    createAnswer(qid,u,content){if(!admin(u))throw new Error('관리자 권한이 필요합니다.');const all=read(),item=all.find(x=>String(x.id)===String(qid)),text=String(content||'').trim();if(!item||item.answer)throw new Error('답변을 등록할 수 없습니다.');if(text.length<10||text.length>2000)throw new Error('답변은 10자 이상 2,000자 이하로 입력해주세요.');item.answerHistory=Array.isArray(item.answerHistory)?item.answerHistory:[];item.answer={id:id(),content:text,adminId:u.id??u.email,adminName:u.name||'관리자',createdAt:new Date().toISOString(),updatedAt:null};item.status='ANSWERED';save(all);window.MomoAdminActivity?.log(u,'CREATE_ANSWER','QNA',qid,'문의 답변 등록');notify(item,'고객님의 문의에 답변이 등록되었습니다.');return normalize(item)},
    updateAnswer(qid,u,content){if(!admin(u))throw new Error('관리자 권한이 필요합니다.');const all=read(),item=all.find(x=>String(x.id)===String(qid)),text=String(content||'').trim();if(!item?.answer)throw new Error('답변이 없습니다.');if(text.length<10||text.length>2000)throw new Error('답변은 10자 이상 2,000자 이하로 입력해주세요.');item.answerHistory=Array.isArray(item.answerHistory)?item.answerHistory:[];item.answerHistory.push({...item.answer,archivedAt:new Date().toISOString(),action:'UPDATED'});item.answer={...item.answer,content:text,updatedAt:new Date().toISOString(),adminId:u.id??u.email,adminName:u.name||'관리자'};save(all);window.MomoAdminActivity?.log(u,'UPDATE_ANSWER','QNA',qid,'문의 답변 수정');notify(item,'고객님의 문의 답변이 수정되었습니다.');return normalize(item)},
    deleteAnswer(qid,u){if(!admin(u))throw new Error('관리자 권한이 필요합니다.');const all=read(),item=all.find(x=>String(x.id)===String(qid));if(!item?.answer)throw new Error('답변이 없습니다.');item.answerHistory=Array.isArray(item.answerHistory)?item.answerHistory:[];item.answerHistory.push({...item.answer,archivedAt:new Date().toISOString(),action:'DELETED'});item.answer=null;item.status='PENDING';save(all);window.MomoAdminActivity?.log(u,'DELETE_ANSWER','QNA',qid,'문의 답변 삭제');return normalize(item)},
    saveAdminMemo(qid,u,memo){if(!admin(u))throw new Error('관리자 권한이 필요합니다.');const all=read(),item=all.find(x=>String(x.id)===String(qid));if(!item)throw new Error('문의를 찾을 수 없습니다.');item.adminMemo=String(memo||'').trim();save(all);return normalize(item)},
    getSla(items=read()){const answered=items.filter(x=>x.answer?.createdAt&&x.createdAt);const avg=list=>list.length?Math.round(list.reduce((s,x)=>s+(new Date(x.answer.createdAt)-new Date(x.createdAt)),0)/list.length/60000):0;const today=new Date().toDateString();return{overallMinutes:avg(answered),todayMinutes:avg(answered.filter(x=>new Date(x.answer.createdAt).toDateString()===today))}},
    getInquiryStatusLabel:s=>s==='ANSWERED'?'답변 완료':'답변 대기', getInquiryCategoryLabel:c=>categories[c]||c,
    canEditInquiry:(q,u)=>Boolean(q&&u&&owns(q,u)&&q.status==='PENDING'), canViewInquiry:(q,u)=>Boolean(q&&u&&(admin(u)||owns(q,u)))
  }; window.MomoQna=api;
})();
