(() => {
  if (window.MomoRewards) return;
  const KEYS={users:'momoUsers',benefits:'momo_member_benefits_v1',coupons:'momo_coffee_coupons_v1',history:'momoPointHistory'},locks=new Set();
  const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}},write=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
  const memberKey=user=>String(user?.id||user?.email||'').toLowerCase(),identifier=user=>user?.id??user?.email,isAdmin=user=>user?.role==='ADMIN',createId=()=>`RWD-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`.toUpperCase();
  const getUsers=()=>{const value=read(KEYS.users,[]);return Array.isArray(value)?value:(value?.users||[])},getUser=userId=>getUsers().find(user=>String(user.id)===String(userId)||String(user.email)===String(userId));
  const getPoints=user=>{const benefits=read(KEYS.benefits,{});return Math.max(0,Number(benefits[memberKey(user)]?.points??user?.points??0)||0)};
  function requireAdmin(admin){if(!isAdmin(admin))throw new Error('관리자 권한이 필요합니다.')}
  function changePoints(userId,amount,reason,admin,type){requireAdmin(admin);const value=Math.floor(Number(amount));if(!Number.isFinite(value)||value<1||value>100000)throw new Error('포인트는 1P 이상 100,000P 이하로 입력해 주세요.');if(!String(reason||'').trim())throw new Error('처리 사유를 입력해 주세요.');const lock=`${userId}:${type}`;if(locks.has(lock))throw new Error('이미 처리 중입니다.');locks.add(lock);try{const users=getUsers(),index=users.findIndex(user=>String(user.id)===String(userId)||String(user.email)===String(userId));if(index<0||users[index].role==='ADMIN')throw new Error('회원을 찾을 수 없습니다.');const before=getPoints(users[index]);if(type==='DEDUCT'&&value>before)throw new Error('보유 포인트보다 많이 차감할 수 없습니다.');const after=type==='EARN'?before+value:before-value;users[index]={...users[index],points:after};write(KEYS.users,users);const benefits=read(KEYS.benefits,{});benefits[memberKey(users[index])]={...(benefits[memberKey(users[index])]||{}),points:after};write(KEYS.benefits,benefits);const current=read('momoCurrentUser',null);if(current&&memberKey(current)===memberKey(users[index]))write('momoCurrentUser',{...current,points:after});const history=read(KEYS.history,[]),record={id:createId(),userId:identifier(users[index]),type,amount:value,balanceBefore:before,balanceAfter:after,reason:String(reason).trim(),adminId:identifier(admin),adminName:admin.name||'관리자',createdAt:new Date().toISOString()};history.push(record);write(KEYS.history,history);window.MomoAdminActivity?.log(admin,type==='EARN'?'GRANT_POINTS':'DEDUCT_POINTS','POINT',userId,`포인트 ${type==='EARN'?'적립':'차감'} ${value}P`,{points:before},{points:after});return{user:users[index],history:record}}finally{locks.delete(lock)}}
  function issueCoupon(userId,payload,reason,admin){requireAdmin(admin);const user=getUser(userId);if(!user||user.role==='ADMIN')throw new Error('회원을 찾을 수 없습니다.');if(!String(reason||'').trim())throw new Error('발행 사유를 입력해 주세요.');const value=Number(payload.discountValue||0);if(value<=0)throw new Error('할인 값은 0보다 커야 합니다.');if(payload.expiresAt&&new Date(payload.expiresAt)<new Date())throw new Error('유효기간은 오늘 이후로 선택해 주세요.');const now=new Date().toISOString(),coupon={id:createId(),couponId:String(payload.couponId||payload.id||payload.type||'CUSTOM'),userId:identifier(user),memberKey:memberKey(user),name:payload.name||payload.title||'관리자 발행 쿠폰',title:payload.name||payload.title||'관리자 발행 쿠폰',description:payload.description||'',discountType:String(payload.discountType||'FIXED').toLowerCase(),discountValue:value,minimumAmount:Number(payload.minimumAmount||0),maximumDiscount:payload.maximumDiscount==null?null:Number(payload.maximumDiscount),expiresAt:payload.expiresAt||null,date:payload.expiresAt?new Date(payload.expiresAt).toISOString().slice(0,10).replaceAll('-','.'):'',status:'available',issuedBy:'ADMIN',adminId:identifier(admin),adminName:admin.name||'관리자',issuedReason:String(reason).trim(),issuedAt:now,used:false,usedAt:null,usedOrderId:null,revoked:false,revokedAt:null,revokedReason:null};const coupons=read(KEYS.coupons,[]);coupons.unshift(coupon);write(KEYS.coupons,coupons);window.MomoAdminActivity?.log(admin,'ISSUE_COUPON','COUPON',coupon.id,`쿠폰 발행: ${coupon.title}`,null,{userId:coupon.userId,title:coupon.title});return coupon}
  function revokeCoupon(couponId,reason,admin){requireAdmin(admin);if(!String(reason||'').trim())throw new Error('회수 사유를 입력해 주세요.');const coupons=read(KEYS.coupons,[]),coupon=coupons.find(item=>String(item.id)===String(couponId));if(!coupon)throw new Error('쿠폰을 찾을 수 없습니다.');if(coupon.used||coupon.status==='used')throw new Error('이미 사용된 쿠폰은 회수할 수 없습니다.');if(coupon.revoked)throw new Error('이미 회수된 쿠폰입니다.');coupon.revoked=true;coupon.revokedAt=new Date().toISOString();coupon.revokedReason=String(reason).trim();coupon.status='revoked';write(KEYS.coupons,coupons);window.MomoAdminActivity?.log(admin,'REVOKE_COUPON','COUPON',coupon.id,`쿠폰 회수: ${coupon.title}`,{status:'available'},{status:'revoked'});return coupon}
  window.MomoRewards={isAdmin,getPoints,getPointHistory:()=>read(KEYS.history,[]),getCoupons:()=>read(KEYS.coupons,[]),getUser,userKey:memberKey,grantPoints:(id,amount,reason,admin)=>changePoints(id,amount,reason,admin,'EARN'),deductPoints:(id,amount,reason,admin)=>changePoints(id,amount,reason,admin,'DEDUCT'),issueCoupon,revokeCoupon};
})();
