(() => {
  if (!window.MomoAdmin || !window.MomoQna) return;
  MomoAdmin.requireAdmin();
  const admin = MomoAdmin.user;
  const perPage = 10;
  let page = 1;
  let selectedId = null;
  let lastDrawerTrigger = null;
  let toastTimer = null;
  const $ = (selector) => document.querySelector(selector);
  const elements = { summary:$('#qnaSummary'), search:$('#qnaSearch'), status:$('#statusFilter'), category:$('#categoryFilter'), period:$('#periodFilter'), sort:$('#sortFilter'), reset:$('#resetQnaFilters'), rows:$('#qnaRows'), empty:$('#qnaEmpty'), result:$('#qnaResultCount'), pagination:$('#qnaPagination'), drawer:$('#qnaDrawer'), backdrop:$('#qnaDrawerBackdrop'), close:$('#closeQnaDrawer'), content:$('#qnaDrawerContent'), toast:$('#qnaToast') };
  const esc = (value) => escapeHtml(String(value ?? ''));
  const validDate = (value) => { const date=new Date(value); return Number.isNaN(date.getTime())?null:date };
  const dateTime = (value) => { const date=validDate(value); return date?new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(date):'-' };
  const day = (value) => validDate(value)?.toDateString() || '';
  const duration = (minutes) => { const safe=Number.isFinite(Number(minutes))?Math.max(0,Math.round(Number(minutes))):0; return safe < 60 ? `${safe}분` : `${Math.floor(safe/60)}시간 ${safe%60}분` };
  const showToast = (message) => { clearTimeout(toastTimer); elements.toast.textContent=message; elements.toast.hidden=false; toastTimer=setTimeout(()=>{elements.toast.hidden=true},2300) };
  Object.entries(MomoQna.categories).forEach(([value,label])=>elements.category.add(new Option(label,value)));

  const filteredInquiries = () => {
    const all=MomoQna.getInquiries(),now=Date.now(),today=day(new Date()),term=elements.search.value.trim().toLowerCase(),days=Number(elements.period.value)||0,cutoff=days?now-(days-1)*86400000:0;
    const rows=all.filter((inquiry)=>{const text=`${inquiry.userName||''} ${inquiry.userEmail||''} ${inquiry.title||''} ${inquiry.content||''}`.toLowerCase();const created=validDate(inquiry.createdAt)?.getTime()||0;return(!elements.status.value||inquiry.status===elements.status.value)&&(!elements.category.value||inquiry.category===elements.category.value)&&(!term||text.includes(term))&&(!cutoff||(elements.period.value==='today'?day(inquiry.createdAt)===today:created>=cutoff))});
    rows.sort((a,b)=>elements.sort.value==='pending'?(a.status===b.status?(validDate(b.createdAt)?.getTime()||0)-(validDate(a.createdAt)?.getTime()||0):a.status==='PENDING'?-1:1):(elements.sort.value==='asc'?1:-1)*((validDate(a.createdAt)?.getTime()||0)-(validDate(b.createdAt)?.getTime()||0)));
    return {all,rows};
  };
  const renderSummary = (all) => { const today=day(new Date()),sla=MomoQna.getSla(all); const cards=[['전체 문의',all.length,'누적 접수 문의'],['답변 대기',all.filter(q=>q.status==='PENDING').length,'처리가 필요한 문의'],['오늘 문의',all.filter(q=>day(q.createdAt)===today).length,'오늘 새로 접수'],['평균 응답 시간',duration(sla.overallMinutes),'전체 답변 기준']]; elements.summary.innerHTML=cards.map(([label,value,description])=>`<article><i aria-hidden="true"></i><div><small>${label}</small><strong>${value}</strong><p>${description}</p></div></article>`).join('') };
  const renderPagination = (pages) => { elements.pagination.innerHTML=pages<=1?'':Array.from({length:pages},(_,index)=>`<button type="button" data-page="${index+1}" ${page===index+1?'aria-current="page"':''}>${index+1}</button>`).join('') };
  const render = () => { const {all,rows}=filteredInquiries();renderSummary(all);const pages=Math.max(1,Math.ceil(rows.length/perPage));page=Math.min(page,pages);const visible=rows.slice((page-1)*perPage,page*perPage);elements.result.textContent=`총 ${rows.length}건`;elements.empty.hidden=rows.length>0;$('.qna-table-wrap').hidden=rows.length===0;elements.rows.innerHTML=visible.map((q)=>{const answered=q.status==='ANSWERED';return`<tr><td data-label="회원"><div class="customer-cell"><span><strong>${esc(q.userName||'-')}</strong><small>${esc(q.userEmail)}</small></span></div></td><td data-label="문의 제목"><div class="inquiry-title"><strong>${esc(q.title)}</strong><small>${esc(q.content).slice(0,70)}${String(q.content||'').length>70?'…':''}</small></div></td><td data-label="문의 유형"><span class="qna-type">${esc(MomoQna.getInquiryCategoryLabel(q.category))}</span></td><td data-label="접수 시간"><span class="qna-time">${dateTime(q.createdAt)}</span></td><td data-label="상태"><span class="qna-status ${answered?'answered':'pending'}">${esc(MomoQna.getInquiryStatusLabel(q.status))}</span></td><td data-label="담당자">${esc(q.answer?.adminName||'-')}</td><td data-label="작업"><button class="drawer-open-button" type="button" data-inquiry="${esc(q.id)}" aria-label="${esc(q.title)} 문의 처리"></button></td></tr>`}).join('');renderPagination(pages) };

  const renderDrawer = () => { const q=MomoQna.getInquiryById(selectedId);if(!q){closeDrawer();return}const history=[...(q.answerHistory||[]),...(q.answer?[q.answer]:[])];elements.content.innerHTML=`<section class="drawer-inquiry-head"><div class="drawer-meta"><span class="qna-type">${esc(MomoQna.getInquiryCategoryLabel(q.category))}</span><span class="qna-status ${q.status==='ANSWERED'?'answered':'pending'}">${esc(MomoQna.getInquiryStatusLabel(q.status))}</span></div><h3>${esc(q.title)}</h3><p>${esc(q.userName||'-')} · ${esc(q.userEmail)} · ${dateTime(q.createdAt)}</p></section><section class="drawer-section"><h3>문의 내용</h3>${q.orderNumber?`<p>주문번호 <strong>${esc(q.orderNumber)}</strong></p>`:''}<div class="inquiry-body">${esc(q.content)}</div></section><section class="drawer-section"><h3>첨부파일</h3><div class="attachment-placeholder">등록된 첨부파일이 없습니다.</div></section><section class="drawer-section"><h3>관리자 메모</h3><textarea id="drawerMemo" maxlength="1000" placeholder="고객에게 보이지 않는 내부 메모입니다.">${esc(q.adminMemo)}</textarea><div class="drawer-actions"><button type="button" data-save-memo>메모 저장</button></div></section><section class="drawer-section answer-editor"><h3>${q.answer?'답변 수정':'답변 작성'}</h3><form id="drawerAnswerForm"><textarea name="content" minlength="10" maxlength="2000" required placeholder="고객에게 전달할 답변을 작성해주세요.">${q.answer?esc(q.answer.content):''}</textarea><div class="editor-meta"><span><b id="drawerAnswerCount">${q.answer?.content.length||0}</b> / 2000</span><span>${q.answer?'등록된 답변을 수정합니다.':'10자 이상 작성해 주세요.'}</span></div><div class="drawer-actions">${q.answer?'<button class="delete" type="button" data-delete-answer>답변 삭제</button>':''}<button class="primary" type="submit">${q.answer?'답변 수정':'답변 등록'}</button></div></form></section><section class="drawer-section"><h3>답변 이력</h3><div class="answer-history">${history.length?history.map((answer,index)=>`<article><strong>${index+1}차 답변 ${answer.action?`· ${esc(answer.action)}`:''}</strong><p>${esc(answer.content)}</p><small>${esc(answer.adminName||'관리자')} · ${dateTime(answer.updatedAt||answer.createdAt)}</small></article>`).join(''):'<p>아직 답변 이력이 없습니다.</p>'}</div></section>`;
    const form=$('#drawerAnswerForm'),textarea=form.content,count=$('#drawerAnswerCount');textarea.addEventListener('input',()=>{count.textContent=textarea.value.length});form.addEventListener('submit',async(event)=>{event.preventDefault();if(!form.reportValidity())return;try{q.answer?MomoQna.updateAnswer(q.id,admin,textarea.value):MomoQna.createAnswer(q.id,admin,textarea.value);showToast(q.answer?'답변이 수정되었습니다.':'답변이 등록되었습니다.');closeDrawer();render()}catch(error){showToast(error.message)}});$('[data-save-memo]').addEventListener('click',()=>{try{MomoQna.saveAdminMemo(q.id,admin,$('#drawerMemo').value);showToast('관리자 메모가 저장되었습니다.')}catch(error){showToast(error.message)}});$('[data-delete-answer]')?.addEventListener('click',async()=>{if(!await MomoAdmin.confirm('답변을 삭제하고 문의를 답변 대기로 변경할까요?','답변 삭제'))return;MomoQna.deleteAnswer(q.id,admin);showToast('답변이 삭제되었습니다.');renderDrawer();render()}) };
  const openDrawer = (id,trigger) => {selectedId=id;lastDrawerTrigger=trigger;renderDrawer();elements.backdrop.hidden=false;elements.drawer.classList.add('is-open');elements.drawer.setAttribute('aria-hidden','false');document.body.classList.add('qna-drawer-visible');elements.close.focus()};
  const closeDrawer = () => {elements.drawer.classList.remove('is-open');elements.drawer.setAttribute('aria-hidden','true');elements.backdrop.hidden=true;document.body.classList.remove('qna-drawer-visible');selectedId=null;lastDrawerTrigger?.focus()};

  [elements.search,elements.status,elements.category,elements.period,elements.sort].forEach(control=>control.addEventListener('input',()=>{page=1;render()}));elements.reset.addEventListener('click',()=>{elements.search.value='';elements.status.value='';elements.category.value='';elements.period.value='all';elements.sort.value='pending';page=1;render()});elements.rows.addEventListener('click',(event)=>{const button=event.target.closest('[data-inquiry]');if(button)openDrawer(button.dataset.inquiry,button)});elements.pagination.addEventListener('click',(event)=>{const button=event.target.closest('[data-page]');if(button){page=Number(button.dataset.page);render()}});elements.close.addEventListener('click',closeDrawer);elements.backdrop.addEventListener('click',closeDrawer);document.addEventListener('keydown',(event)=>{if(event.key==='Escape'&&elements.drawer.classList.contains('is-open'))closeDrawer()});window.addEventListener('storage',(event)=>{if(event.key===MomoQna.key){render();if(selectedId)renderDrawer()}});render();
})();
