(() => {
  'use strict';
  if(!window.MomoAdmin || !window.MomoAdminAnalytics) return;
  const $=selector=>document.querySelector(selector), read=(key,fallback)=>MomoAdmin.read(key,fallback);
  const won=value=>`${Math.max(0,Number(value)||0).toLocaleString('ko-KR')}원`, number=value=>Math.max(0,Number(value)||0).toLocaleString('ko-KR');
  const validDate=value=>{const date=new Date(value);return Number.isNaN(date.getTime())?null:date};
  const rawUsers=read('momoUsers',[]), users=(Array.isArray(rawUsers)?rawUsers:(rawUsers?.users||[])).filter(user=>user.role!=='ADMIN');
  let chartUnit='day', currentSales=null;
  const orderUserKey=order=>String(order.userId||order.userEmail||order.email||'guest').toLowerCase();

  function comparison(current,previous){if(!previous)return current?'▲ 지난 기간 대비 신규':'지난 기간 대비 변동 없음';const rate=Math.abs((current-previous)/previous*100).toFixed(1);return current>=previous?`▲ 지난 기간 대비 ${rate}%`:`▼ 지난 기간 대비 ${rate}%`}
  function getPeriodData(days){const current=MomoAdminAnalytics.sales(days),end=new Date();end.setHours(0,0,0,0);const previousEnd=new Date(end);previousEnd.setDate(previousEnd.getDate()-days);const previousStart=new Date(previousEnd);previousStart.setDate(previousStart.getDate()-days+1);return{current,previous:MomoAdminAnalytics.sales(days,previousStart,previousEnd)}}
  function groupSales(byDay,unit){const entries=Object.entries(byDay).sort(([a],[b])=>a.localeCompare(b));if(unit==='day')return entries;const grouped={};entries.forEach(([key,value])=>{const date=new Date(`${key}T00:00:00`);let label;if(unit==='month')label=`${date.getFullYear()}.${String(date.getMonth()+1).padStart(2,'0')}`;else{const monday=new Date(date);monday.setDate(date.getDate()-((date.getDay()+6)%7));label=`${monday.getMonth()+1}.${monday.getDate()} 주`}grouped[label]=(grouped[label]||0)+value});return Object.entries(grouped)}
  function renderChart(){const rows=groupSales(currentSales.byDay,chartUnit),container=$('#salesChart');if(!rows.length){container.innerHTML='<div class="chart-empty">아직 집계할 매출 데이터가 없습니다.</div>';return}const width=760,height=270,pad={left:42,right:16,top:20,bottom:34},max=Math.max(1,...rows.map(row=>row[1])),x=index=>pad.left+index*((width-pad.left-pad.right)/Math.max(1,rows.length-1)),y=value=>pad.top+(height-pad.top-pad.bottom)*(1-value/max),barWidth=Math.min(40,(width-pad.left-pad.right)/rows.length*.42),points=rows.map(([label,value],index)=>`${x(index)},${y(value)}`).join(' '),area=`${pad.left},${height-pad.bottom} ${points} ${x(rows.length-1)},${height-pad.bottom}`;container.innerHTML=`<svg class="sales-svg" viewBox="0 0 ${width} ${height}" preserveAspectRatio="none" aria-hidden="true">${[0,.25,.5,.75,1].map(step=>`<line class="grid" x1="${pad.left}" y1="${y(max*step)}" x2="${width-pad.right}" y2="${y(max*step)}"/><text x="0" y="${y(max*step)+4}">${Math.round(max*step/10000)}만</text>`).join('')}<polygon class="area" points="${area}"/>${rows.map(([label,value],index)=>`<rect x="${x(index)-barWidth/2}" y="${y(value)}" width="${barWidth}" height="${height-pad.bottom-y(value)}" rx="5" fill="#e8d4c4"><title>${label} · ${won(value)}</title></rect>`).join('')}<polyline class="line" points="${points}"/>${rows.map(([label,value],index)=>`<circle class="dot" cx="${x(index)}" cy="${y(value)}" r="4"><title>${label} · ${won(value)}</title></circle><text x="${x(index)}" y="${height-9}" text-anchor="middle">${label.slice(-5)}</text>`).join('')}</svg>`}
  function render(){
    const days=Number($('#analyticsPeriod').value),{current:sales,previous}=getPeriodData(days);currentSales=sales;const orders=sales.rows,allOrders=MomoAdminAnalytics.orders(),menus=MomoAdminAnalytics.menus().slice(0,10),members=MomoAdminAnalytics.members();
    const periodStart=new Date();periodStart.setDate(periodStart.getDate()-days+1);periodStart.setHours(0,0,0,0);const newMembers=users.filter(user=>{const date=validDate(user.createdAt||user.joinedAt||user.signupAt);return date&&date>=periodStart}).length;
    const byCustomer={};allOrders.forEach(order=>{const key=orderUserKey(order);if(key!=='guest')byCustomer[key]=(byCustomer[key]||0)+1});const customerCounts=Object.values(byCustomer),reorderRate=customerCounts.length?customerCounts.filter(count=>count>1).length/customerCounts.length*100:0;
    const previousAverage=previous.count?Math.round(previous.total/previous.count):0;
    const kpis=[['₩','총 매출',won(sales.total),comparison(sales.total,previous.total)],['▢','주문 건수',`${number(sales.count)}건`,comparison(sales.count,previous.count)],['♙','회원 수',`${number(users.length)}명`,`${days}일 기준 전체 고객`],['◇','최고 일 매출',sales.highest?`${sales.highest[0]} · ${won(sales.highest[1])}`:'-',`최근 ${days}일 기준`]];
    $('#salesMetrics').innerHTML=kpis.map(([icon,label,value,desc])=>`<article class="analytics-kpi"><i aria-hidden="true">${icon}</i><div><small>${label}</small><strong>${value}</strong><small>${desc}</small></div></article>`).join('');renderChart();$('#salesSummary').textContent=`최근 ${days}일 매출 ${won(sales.total)} · 주문 ${number(sales.count)}건`;
    const maxMenu=Math.max(1,...menus.map(menu=>menu.quantity));$('#menuRanking').innerHTML=menus.length?menus.map((menu,index)=>`<div class="rank-row"><b>${index+1}</b><span title="${menu.name}">${menu.name}</span><div class="rank-track"><i style="width:${menu.quantity/maxMenu*100}%"></i></div><small>${number(menu.quantity)}개 · ${won(menu.sales)}</small></div>`).join(''):'<div class="chart-empty">판매 데이터가 없습니다.</div>';
    const weekdayNames=['일요일','월요일','화요일','수요일','목요일','금요일','토요일'],weekdayValues=Array(7).fill(0);orders.forEach(order=>{const date=validDate(order.createdAt);if(date)weekdayValues[date.getDay()]+=MomoAdminAnalytics.amount(order)});const maxWeek=Math.max(1,...weekdayValues);$('#weekdaySales').innerHTML=[1,2,3,4,5,6,0].map(day=>`<div class="weekday-row"><span>${weekdayNames[day]}</span><i><b style="width:${weekdayValues[day]/maxWeek*100}%"></b></i><strong>${won(weekdayValues[day])}</strong></div>`).join('');
    const hours=Array(24).fill(0);orders.forEach(order=>{const date=validDate(order.createdAt);if(date)hours[date.getHours()]++});const maxHour=Math.max(1,...hours);$('#hourHeatmap').innerHTML=hours.map((count,hour)=>{const intensity=count/maxHour;return`<div class="heat-cell" style="background:rgba(126,83,62,${.08+intensity*.82})" title="${String(hour).padStart(2,'0')}:00 · ${count}건">${String(hour).padStart(2,'0')}</div>`}).join('');
    const orderingMembers=new Set(allOrders.map(orderUserKey)).size,memberOrderRatio=allOrders.length?allOrders.filter(order=>orderUserKey(order)!=='guest').length/allOrders.length*100:0;$('#memberInsights').innerHTML=[['신규 회원',`${newMembers}명`],['전체 회원',`${users.length}명`],['재방문율',`${reorderRate.toFixed(1)}%`],['회원 주문 비율',`${memberOrderRatio.toFixed(1)}%`]].map(([label,value])=>`<div class="mini-insight"><small>${label}</small><strong>${value}</strong></div>`).join('');
    const cancelled=(read('momo_coffee_orders_v1',[])||[]).filter(order=>String(order.status).toLowerCase()==='cancelled'),cancelRate=(allOrders.length+cancelled.length)?cancelled.length/(allOrders.length+cancelled.length)*100:0,busiest=hours.indexOf(Math.max(...hours));$('#orderInsights').innerHTML=[['평균 주문 금액',won(sales.average)],['주문 취소율',`${cancelRate.toFixed(1)}%`],['회원 주문 비율',`${memberOrderRatio.toFixed(1)}%`],['최다 주문 시간',hours[busiest]?`${String(busiest).padStart(2,'0')}:00 ~ ${String((busiest+1)%24).padStart(2,'0')}:00`:'-']].map(([label,value])=>`<div class="text-insight"><span>${label}</span><strong>${value}</strong></div>`).join('');
    const pending=(read('momoInquiries',[])||[]).filter(item=>item.status==='PENDING').length,top=menus[0],alerts=[sales.highest&&['₩','최고 매출일',`${sales.highest[0]} · ${won(sales.highest[1])}`],top&&['★','인기 메뉴',`${top.name} · ${top.quantity}개 판매`],['♙','신규 회원',`${days}일간 ${newMembers}명 가입`],pending&&['□','답변 대기 문의',`${pending}건의 확인이 필요합니다.`]].filter(Boolean);$('#analyticsAlerts').innerHTML=alerts.map(([icon,title,text])=>`<div class="alert-row"><i aria-hidden="true">${icon}</i><span><strong>${title}</strong><small>${text}</small></span><time>현재 기준</time></div>`).join('');
  }
  $$('.chart-tabs button').forEach(button=>button.addEventListener('click',()=>{chartUnit=button.dataset.chartUnit;$$('.chart-tabs button').forEach(item=>item.classList.toggle('active',item===button));renderChart()}));
  function $$(selector){return[...document.querySelectorAll(selector)]}
  $('#analyticsRefresh').addEventListener('click',render);$('#analyticsPeriod').addEventListener('change',render);window.addEventListener('storage',render);render();
})();
