(() => {
  const CURRENT_USER_KEY='momoCurrentUser', LATEST_ORDER_KEY='momo_coffee_latest_order_v1';
  const stores=[{id:'jamsil',name:'모모커피 잠실점',address:'서울 송파구 올림픽로 00',hours:'08:00 - 22:00',eta:10},{id:'seokchon',name:'모모커피 석촌호수점',address:'서울 송파구 석촌호수로 00',hours:'09:00 - 22:00',eta:12},{id:'magok',name:'모모커피 마곡점',address:'서울 강서구 마곡중앙로 00',hours:'08:00 - 21:00',eta:15},{id:'seongsu',name:'모모커피 성수점',address:'서울 성동구 연무장길 00',hours:'09:00 - 22:00',eta:12},{id:'yeonnam',name:'모모커피 연남점',address:'서울 마포구 동교로 00',hours:'10:00 - 22:00',eta:15}];
  const methods={card:['/assets/icons/payment-card.svg','신용·체크카드','일반 카드로 결제합니다.'],kakao:['/assets/icons/payment-kakao.svg','카카오페이','카카오페이로 간편하게 결제합니다.'],naver:['/assets/icons/payment-naver.svg','네이버페이','네이버페이로 간편하게 결제합니다.'],toss:['/assets/icons/payment-toss.svg','토스페이','토스페이로 빠르게 결제합니다.']};
  const $=s=>document.querySelector(s), money=n=>`${Math.max(0,Number(n)||0).toLocaleString('ko-KR')}원`;
  let user=null,cart=[],coupon=null,discount=0,points=0,submitting=false;
  try{user=JSON.parse(localStorage.getItem(CURRENT_USER_KEY)||'null')}catch{}
  const isMember=Boolean(user);
  let isBuyNow=false;try{const routeItem=new URLSearchParams(location.hash.replace(/^#/,'')).get('buyNow'),raw=routeItem||localStorage.getItem('momoBuyNowItem')||sessionStorage.getItem('momoPendingBuyNowItem')||'null';const buyNow=JSON.parse(raw);isBuyNow=Boolean(buyNow?.menuId&&Number(buyNow?.quantity)>0);cart=isBuyNow?[buyNow]:getCart()}catch{try{cart=getCart()}catch{cart=[]}}
  let operationSettings={};try{operationSettings=JSON.parse(localStorage.getItem('momoOperationSettings')||'{}')}catch{}
  const invalid=cart.filter(i=>!getMenuById(i.menuId)||getMenuById(i.menuId)?.soldOut||getMenuById(i.menuId)?.isSoldOut||!Number.isFinite(Number(i.price))||Number(i.price)<0||!Number.isInteger(Number(i.quantity))||Number(i.quantity)<1);
  if(operationSettings.orderEnabled===false||operationSettings.pickupEnabled===false||operationSettings.maintenanceMode===true){alert('현재 온라인 주문이 일시 중지되었습니다.');location.replace('/basket/list.html');return}
  if(!cart.length){location.replace('/basket/list.html');return}
  const subtotal=cart.reduce((s,i)=>s+Number(i.price)*Number(i.quantity),0);
  const benefit=isMember?(window.MomoLoyalty?.getBenefit?.()||{points:Number(user.points)||0}):{points:0};
  const refs={form:$('#checkoutForm'),alert:$('#checkoutAlert'),items:$('#orderItems'),stores:$('#storeOptions'),coupons:$('#couponSelect'),points:$('#pointInput'),stamp:$('#stampRewardInput'),panel:$('#paymentPanel'),pay:$('#payButton')};
  const rewardNotice=document.createElement('p');rewardNotice.className='checkout-reward-notice';rewardNotice.setAttribute('aria-live','polite');refs.pay.before(rewardNotice);const syncRewardNotice=()=>{const amount=Number(($('#finalAmount').textContent||'').replace(/[^0-9]/g,''))||0;rewardNotice.innerHTML=isMember?`<span>REWARD</span><strong>${Math.floor(amount*.05).toLocaleString('ko-KR')}P 적립 예정</strong><small>결제 완료 시 최종 결제금액의 5%가 자동 적립됩니다.</small>`:`<span>GUEST ORDER</span><strong>비회원 주문으로 진행합니다.</strong><small>쿠폰·포인트 적립 및 사용은 로그인한 회원에게만 제공됩니다.</small>`};new MutationObserver(syncRewardNotice).observe($('#finalAmount'),{childList:true,characterData:true,subtree:true});syncRewardNotice();
  const englishNames={1:'Vanilla Latte',2:'Cream Einspanner',3:'Americano',4:'Cafe Latte',5:'Matcha Latte',6:'Strawberry Cream Latte',7:'Yuja Chamomile Tea',8:'Peach Iced Tea',9:'Strawberry Cream Cake',10:'Chocolate Cake',11:'Butter Croissant',12:'Momo Honey Bread'};
  const optionText=o=>Object.values(o||{}).filter(Boolean).join(' · ');
  refs.items.innerHTML=cart.map(i=>{const m=getMenuById(i.menuId)||i;const src=m.image?(m.image.startsWith('/')?m.image:'/'+m.image.replace(/^\.\.\//,'')):'/assets/images/momo-face-cute.png';return `<article class="order-item"><img src="${escapeHtml(src)}" alt="${escapeHtml(i.name)}"><div><h3>${escapeHtml(i.name)}</h3><p class="english-name">${escapeHtml(m.englishName||englishNames[i.menuId]||getCategoryName(i.category))}</p><p>${escapeHtml(optionText(i.options)||'기본 옵션')} · ${i.quantity}개</p></div><strong>${money(i.price*i.quantity)}</strong></article>`}).join('');
  refs.stores.innerHTML=stores.map(s=>`<label class="radio-card"><input type="radio" name="store" value="${s.id}"><strong>${s.name}</strong><span>${s.address}</span><small>${s.hours} · 약 ${s.eta}분</small></label>`).join('');
  $('#customerInfo').innerHTML=isMember?`<div><dt>이름</dt><dd>${escapeHtml(user.name||'-')}</dd></div><div><dt>이메일</dt><dd>${escapeHtml(user.email||'-')}</dd></div><div><dt>연락처</dt><dd>${escapeHtml(user.phone||user.phoneNumber||'-')}</dd></div>`:`<div class="guest-field"><label for="guestName">주문자 이름</label><input id="guestName" name="guestName" required maxlength="30" autocomplete="name" placeholder="이름을 입력해주세요."></div><div class="guest-field"><label for="guestPhone">연락처</label><input id="guestPhone" name="guestPhone" required inputmode="tel" maxlength="20" autocomplete="tel" placeholder="010-0000-0000"></div><div class="guest-field"><label for="guestEmail">이메일 <small>(선택)</small></label><input id="guestEmail" name="guestEmail" type="email" maxlength="100" autocomplete="email" placeholder="order@example.com"></div>`;
  if(!isMember){const profileLink=document.querySelector('.customer-section .section-title a');if(profileLink){profileLink.removeAttribute('href');profileLink.textContent='비회원 주문'}}
  if(!isMember)refs.form.addEventListener('submit',()=>{user={id:`GUEST-${Date.now().toString(36).toUpperCase()}`,name:$('#guestName').value.trim(),phone:$('#guestPhone').value.trim(),email:$('#guestEmail').value.trim()}} ,true);
  $('#availablePoints').textContent=money(benefit.points).replace('원','P');
  const coupons=isMember?getMomoCouponsForUser(user).filter(c=>c.status==='available'&&!c.used&&!c.revoked):[];refs.coupons.insertAdjacentHTML('beforeend',coupons.map(c=>`<option value="${c.id}">${escapeHtml(c.title)}</option>`).join(''));
  if(!isMember){refs.coupons.disabled=true;refs.points.disabled=true;$('#useAllPoints').disabled=true;$('#couponMessage').textContent='비회원 주문에서는 쿠폰과 포인트 혜택을 사용할 수 없습니다.';refs.coupons.closest('.section-card')?.classList.add('guest-benefits-disabled')}
  $('#paymentMethods').innerHTML=Object.entries(methods).map(([id,m])=>`<label class="radio-card payment-method"><input type="radio" name="payment" value="${id}"><img src="${m[0]}" alt="" class="payment-logo"><span>${m[1]}</span><small>${m[2]}</small></label>`).join('');
  function selected(name){return refs.form.elements[name]?.value||''} function maxPoints(){return Math.min(Number(benefit.points)||0,Math.max(0,subtotal-discount))}
  function customerValid(){if(isMember)return true;return Boolean($('#guestName')?.value.trim()&&$('#guestPhone')?.value.trim())}
  function cardValid(){if(selected('payment')!=='card')return true;return [...refs.panel.querySelectorAll('[required]')].every(i=>i.checkValidity())}
  function getValidationIssue(){const total=Math.max(0,subtotal-discount-points);if(invalid.length)return{target:$('#itemsSection'),message:'현재 주문할 수 없는 메뉴가 포함되어 있습니다.'};if(!selected('store'))return{target:$('#storeSection'),message:'픽업 매장을 선택해주세요.'};if(!customerValid())return{target:document.querySelector('.customer-section'),message:'주문자 이름과 연락처를 확인해주세요.'};if(total>0&&!selected('payment'))return{target:$('#paymentSection'),message:'결제 수단을 선택해주세요.'};if(!cardValid())return{target:$('#paymentSection'),message:'카드 결제 정보를 모두 올바르게 입력해주세요.'};if(![...document.querySelectorAll('.required-term')].every(i=>i.checked))return{target:$('#termsSection'),message:'주문 진행을 위해 필수 약관에 동의해주세요.'};return null}
  function update(){points=isMember?Math.min(Math.max(0,Math.floor(Number(refs.points.value)||0)),maxPoints()):0;refs.points.value=points;const total=Math.max(0,subtotal-discount-points);$('#subtotal').textContent=money(subtotal);$('#couponDiscount').textContent=discount?`-${money(discount)}`:'0원';$('#pointDiscount').textContent=points?`-${money(points)}`:'0원';$('#finalAmount').textContent=money(total);$('#itemCount').textContent=cart.reduce((s,i)=>s+Number(i.quantity),0);const store=stores.find(s=>s.id===selected('store'));$('#selectedStore').textContent=store?.name||'선택 전';$('#selectedPayment').textContent=total===0?'무료 주문':(methods[selected('payment')]?.[1]||'선택 전');refs.pay.textContent=total===0?'무료 주문 완료':`${money(total)} 결제하기`;const ready=!getValidationIssue();refs.pay.classList.toggle('is-ready',ready);refs.pay.setAttribute('aria-disabled',String(!ready));refs.pay.disabled=submitting||invalid.length>0}
  refs.coupons.addEventListener('change',()=>{coupon=coupons.find(c=>String(c.id)===refs.coupons.value)||null;const result=coupon?calculateMomoCoupon(coupon,cart):{eligible:true,discount:0,reason:''};if(!result.eligible){coupon=null;refs.coupons.value='';discount=0}else discount=result.discount;$('#couponMessage').textContent=result.reason||'';update()});
  refs.points.addEventListener('input',update);$('#useAllPoints').addEventListener('click',()=>{refs.points.value=maxPoints();update()});
  refs.stamp.closest('.checkout-benefit-extra').hidden=true;
  refs.form.addEventListener('change',e=>{if(e.target.name==='payment'){const id=e.target.value;if(id==='card')refs.panel.innerHTML=`<div class="card-form"><label class="wide">카드사 선택<select required><option value="">선택해 주세요</option><option>모모카드</option><option>해피카드</option></select></label><label class="wide">카드번호<input required inputmode="numeric" pattern="[0-9]{16}" maxlength="16" autocomplete="off" placeholder="숫자 16자리"></label><label>유효기간<input required inputmode="numeric" pattern="[0-9]{4}" maxlength="4" autocomplete="off" placeholder="MMYY"></label><label>비밀번호 앞 2자리<input required type="password" inputmode="numeric" pattern="[0-9]{2}" maxlength="2" autocomplete="off"></label><label>생년월일 6자리<input required inputmode="numeric" pattern="[0-9]{6}" maxlength="6" autocomplete="off"></label><label>할부 선택<select required><option>일시불</option><option>2개월</option><option>3개월</option></select></label><p class="wide mock-notice">실제 결제가 진행되지 않는 포트폴리오용 화면입니다.</p></div>`;else refs.panel.innerHTML=`<div class="easy-panel"><strong>${methods[id][1]}를 선택하셨습니다.</strong><p>결제하기 버튼을 누르면 모의 결제가 진행됩니다. 계정 정보는 입력하지 않습니다.</p></div>`}update()});
  refs.form.addEventListener('input',update);$('#agreeAll').addEventListener('change',e=>{document.querySelectorAll('.required-term').forEach(i=>i.checked=e.target.checked);update()});
  if(invalid.length){refs.alert.hidden=false;refs.alert.innerHTML=`<strong>품절된 메뉴가 포함되어 있어 주문할 수 없습니다.</strong><p>${invalid.map(i=>escapeHtml(i.name)).join(', ')}</p><a href="/basket/list.html">장바구니 확인</a>`}
  refs.form.addEventListener('submit',async e=>{e.preventDefault();update();const issue=getValidationIssue();if(issue){refs.alert.hidden=false;refs.alert.textContent=issue.message;refs.alert.focus({preventScroll:true});issue.target?.scrollIntoView({behavior:'smooth',block:'center'});issue.target?.querySelector('input,select,button')?.focus({preventScroll:true});return}refs.alert.hidden=true;if(submitting)return;submitting=true;update();refs.pay.textContent='결제를 확인하고 있어요…';await new Promise(r=>setTimeout(r,900));try{const store=stores.find(s=>s.id===selected('store'));const total=Math.max(0,subtotal-discount-points);const now=new Date(),id=generateId();const orderNumber=`MOMO-${now.toISOString().slice(0,10).replaceAll('-','')}-${now.getTime().toString().slice(-6)}`;const order={id,orderNumber,userId:user.id??user.email,userEmail:user.email,customerName:user.name,customerPhone:user.phone||user.phoneNumber||'',items:cart.map(i=>({...i})),subtotal,couponDiscount:discount,pointDiscount:points,totalAmount:total,total,couponId:coupon?.id??null,coupon:coupon?{id:coupon.id,title:coupon.title}:null,usedPoints:points,paymentMethod:total===0?'free':selected('payment'),paymentStatus:'paid',status:'RECEIVED',updatedAt:null,statusHistory:[{status:'RECEIVED',changedAt:now.toISOString(),changedBy:'SYSTEM'}],adminMemo:'',pickupStore:{id:store.id,name:store.name,address:store.address,eta:store.eta},createdAt:now.toISOString(),completedAt:null};const orders=getOrders();if(!orders.some(o=>o.id===id)){orders.push(order);saveOrders(orders)}if(points&&!window.MomoLoyalty?.usePoints?.(points))throw new Error('포인트 처리에 실패했습니다.');if(coupon){const all=getMomoCoupons(),c=all.find(x=>String(x.id)===String(coupon.id));if(c){c.status='used';c.used=true;c.usedAt=now.toISOString();c.orderId=id;c.usedOrderId=id;saveMomoCoupons(all);selectMomoCoupon(null)}}if(!isBuyNow)clearCart();localStorage.removeItem('momoBuyNowItem');localStorage.setItem(LATEST_ORDER_KEY,id);refs.panel.querySelectorAll('input').forEach(i=>i.value='');location.replace(`/orders/complete.html#id=${encodeURIComponent(id)}`)}catch(err){submitting=false;refs.alert.hidden=false;refs.alert.textContent=err.message||'주문 처리 중 문제가 생겼습니다.';refs.alert.focus();update()}});
  let handoff={};try{handoff=JSON.parse(localStorage.getItem('momoCheckoutBenefits')||'{}')||{}}catch{}localStorage.removeItem('momoCheckoutBenefits');
  if(handoff.couponId!=null){refs.coupons.value=String(handoff.couponId);refs.coupons.dispatchEvent(new Event('change'))}
  refs.points.value=Math.max(0,Math.floor(Number(handoff.points)||0));
  update();
})();
