window.MOMO_NOTICES=[
{id:1,category:'매장 안내',title:'모모커피 성수 플래그십 스토어 오픈',description:'빛과 나무가 머무는 새로운 모모커피 공간을 소개합니다.',date:'2026.07.20',image:'../assets/images/news-new-store.png',body:['성수의 조용한 골목에 모모커피의 새로운 플래그십 스토어가 문을 엽니다. 크림색 벽과 따뜻한 오크, 아침 햇살이 자연스럽게 어우러지는 공간입니다.','바리스타 바를 중심으로 창가 라운지와 오픈형 좌석을 배치했습니다. 오픈 후 2주간 멤버십 회원에게 스탬프 1개를 추가 적립합니다.']},
{id:2,category:'메뉴 안내',title:'여름 시즌 메뉴 Peach Collection 출시',description:'복숭아와 딸기의 산뜻함을 담은 여름 한정 메뉴를 만나보세요.',date:'2026.07.15',image:'../assets/images/news-season-menu.png',body:['복숭아의 맑은 향과 딸기의 은은한 산미를 살린 여름 컬렉션을 선보입니다.','2026년 9월 15일까지 판매하며 원재료 수급에 따라 조기 종료될 수 있습니다.']},
{id:3,category:'굿즈',title:'MOMO Daily Objects 신규 굿즈 안내',description:'머그, 텀블러, 키링과 에코백으로 구성된 데일리 컬렉션입니다.',date:'2026.07.12',image:'../assets/images/news-momo-goods.png',body:['매일 손이 가는 소재와 차분한 색으로 완성한 모모 굿즈를 소개합니다.','전국 모모커피 매장과 온라인 상품 메뉴에서 구매할 수 있습니다.']},
{id:4,category:'멤버십',title:'7월 모모 멤버십 등급 혜택 안내',description:'WELCOME부터 VIP까지 월 결제금액에 따른 혜택을 확인하세요.',date:'2026.07.01',image:'../assets/images/event-membership-day.png',body:['회원가입 후 로그인하면 모모 멤버십이 자동으로 활성화됩니다.','월 결제금액에 따라 WELCOME, SILVER, GOLD, VIP 등급이 적용되며 혜택 쿠폰은 자동으로 발급됩니다.']},
{id:5,category:'이벤트',title:'리뷰 작성 포인트 적립 이벤트',description:'주문 경험을 남기면 500포인트를 적립해드립니다.',date:'2026.06.28',image:'../assets/images/event-review.png',body:['주문 후 이벤트 페이지에서 별점과 리뷰를 남겨주세요.','리뷰 등록 즉시 500포인트가 적립되며 작성 내역은 마이페이지에서 확인할 수 있습니다.']},
{id:6,category:'서비스 안내',title:'스탬프 리워드 이용 안내',description:'주문 한 건마다 모모 얼굴 스탬프가 한 개씩 적립됩니다.',date:'2026.06.20',image:'../assets/images/event-new-member.png',body:['메뉴 개수와 관계없이 결제가 완료된 주문 한 건당 스탬프 한 개가 적립됩니다.','10개를 모으면 3,500원 할인 리워드가 자동 발급됩니다.']},
{id:7,category:'기타',title:'일회용 컵 없는 매장 운영 안내',description:'더 나은 내일을 위한 다회용 컵 운영 매장을 안내합니다.',date:'2026.06.12',image:'../assets/images/bi-packaging-system.png',body:['일부 매장에서 다회용 컵 우선 운영을 시작합니다.','개인 텀블러 이용 고객에게는 멤버십 포인트 혜택을 제공합니다.']},
{id:8,category:'매장 안내',title:'연남점 리뉴얼 오픈 안내',description:'더 편안한 좌석과 새로운 바리스타 바로 돌아왔습니다.',date:'2026.06.05',image:'../assets/images/store-yeonnam.png',body:['모모커피 연남점이 새로운 모습으로 문을 엽니다.','리뉴얼 기간 기다려주신 고객분들께 감사드립니다.']},
{id:9,category:'메뉴 안내',title:'모모 하우스 블렌드 원두 변경 안내',description:'더욱 고소하고 긴 여운을 위한 새로운 블렌드를 소개합니다.',date:'2026.05.26',image:'../assets/images/brand-latte-craft.png',body:['브라질과 콜롬비아 원두를 중심으로 캐러멜과 견과의 단맛을 살렸습니다.','에스프레소와 우유 메뉴 모두에서 균형 잡힌 맛을 느낄 수 있습니다.']},
{id:10,category:'이벤트',title:'모모커피 여름 사진 이벤트',description:'나만의 여름 모모 순간을 사진으로 공유해주세요.',date:'2026.05.18',image:'../assets/images/event-hero-lifestyle.png',body:['모모커피와 함께한 여름의 순간을 사진으로 남겨주세요.','선정된 고객에게 시즌 메뉴 쿠폰을 드립니다.']},
{id:11,category:'서비스 안내',title:'모바일 주문 서비스 이용 안내',description:'장바구니부터 쿠폰과 포인트 사용까지 안내해드립니다.',date:'2026.05.10',image:'../assets/images/momo-app-phone-reference.png',body:['메뉴를 장바구니에 담고 쿠폰과 포인트를 선택한 뒤 주문할 수 있습니다.','비회원도 장바구니를 사용할 수 있으며 멤버십 혜택은 로그인 후 적용됩니다.']},
{id:12,category:'기타',title:'고객센터 운영시간 변경 안내',description:'모모커피 고객센터의 상담 운영시간을 확인해주세요.',date:'2026.05.01',image:'../assets/images/news-faq-guide.png',body:['고객센터는 평일 오전 9시부터 오후 6시까지 운영합니다.','주말과 공휴일 문의는 다음 영업일에 순차 답변드립니다.']}
];
