(() => {
  if(!window.MomoAdmin||!window.MomoAdminAnalytics)return;
  const A=MomoAdminAnalytics,$=id=>document.getElementById(id),orders=A.orders(),rawUsers=A.get('momoUsers',[]),users=(Array.isArray(rawUsers)?rawUsers:(rawUsers?.users||[])).filter(u=>u?.role!=='ADMIN'),inquiries=A.get('momoInquiries',[])||[],menus=typeof getMenus==='function'?getMenus():[],settings=MomoAdminSettings?.get()||{};
  const todayKey=A.local(new Date()),todayOrders=orders.filter(o=>A.local(o.createdAt)===todayKey),pending=inquiries.filter(q=>q?.status==='PENDING'),preparing=orders.filter(o=>String(o.status).toUpperCase()==='PREPARING'),soldout=menus.filter(m=>m?.isSoldOut||m?.soldOut),todaySales=todayOrders.reduce((sum,o)=>sum+A.amount(o),0);
  $('heroAdminName').textContent=MomoAdmin.user.name||'관리자';$('heroDate').textContent=MomoAdmin.formatDate(new Date());$('heroStoreState').innerHTML=`<span class="live-dot"></span>${settings.maintenanceMode?'점검 중':settings.orderEnabled===false?'주문 일시 중지':settings.storeOpen===false?'영업 종료':'정상 영업 중'}`;
  const cards=[['오늘 주문 수',`${todayOrders.length}건`,'실제 접수 주문'],['오늘 매출',MomoAdmin.formatMoney(todaySales),'취소·무효 주문 제외'],['답변 대기 문의',`${pending.length}건`,'고객 답변 필요','/admin/qna/list.html'],['제조 중 주문',`${preparing.length}건`,'현재 제조 진행','/admin/orders/list.html'],['전체 회원 수',`${users.length}명`,'관리자 계정 제외','/admin/members/list.html'],['품절 메뉴',`${soldout.length}개`,'판매 상태 확인','/admin/menus/list.html']];
  $('summaryGrid').innerHTML=cards.map(([label,value,desc,url])=>`<${url?'a':'article'} class="summary-card" ${url?`href="${url}"`:''}><span>${label}</span><strong>${value}</strong><p>${desc}</p>${url?'<em>→</em>':''}</${url?'a':'article'}>`).join('');
  $('attentionLinks').innerHTML=`<a href="/admin/orders/list.html">주문 접수 ${orders.filter(o=>String(o.status).toUpperCase()==='RECEIVED').length}건</a><a href="/admin/orders/list.html">제조 중 ${preparing.length}건</a><a href="/admin/qna/list.html">답변 대기 ${pending.length}건</a><a href="/admin/menus/list.html">품절 ${soldout.length}개</a>`;
  const recentOrders=[...orders].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,5);if(!recentOrders.length)MomoAdmin.empty($('recentOrders'),'아직 접수된 주문이 없습니다.','새 주문이 접수되면 여기에 표시됩니다.');else $('recentOrders').innerHTML=`<div class="admin-list">${recentOrders.map(o=>`<a class="admin-row" href="/admin/orders/detail.html?id=${encodeURIComponent(o.id)}"><div><strong>${o.orderNumber||o.id||'-'}</strong><small>${o.customerName||o.userEmail||'고객'}</small></div><span class="status-badge status-${String(o.status).toUpperCase()}">${typeof getOrderStatusLabel==='function'?getOrderStatusLabel(o.status):o.status}</span><time>${MomoAdmin.relativeTime(o.createdAt)}</time></a>`).join('')}</div>`;
  const recentQ=[...inquiries].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,5);if(!recentQ.length)MomoAdmin.empty($('recentInquiries'),'등록된 문의가 없습니다.','새 문의가 등록되면 여기에 표시됩니다.');else $('recentInquiries').innerHTML=`<div class="admin-list">${recentQ.map(q=>`<a class="admin-row" href="/admin/qna/detail.html?id=${encodeURIComponent(q.id)}"><div><strong>${q.title||'제목 없음'}</strong><small>${q.userName||q.userEmail||'고객'}</small></div><span class="status-badge ${q.status==='ANSWERED'?'done':''}">${q.status==='ANSWERED'?'답변 완료':'답변 대기'}</span><time>${MomoAdmin.relativeTime(q.createdAt)}</time></a>`).join('')}</div>`;
  const sales=A.sales(7),days=Object.entries(sales.byDay),max=Math.max(1,...days.map(([,v])=>v));$('dashboardSalesChart').innerHTML=days.length?days.map(([day,value])=>`<i style="height:${Math.max(5,value/max*100)}%" title="${day} ${MomoAdmin.formatMoney(value)}"><span>${day.slice(5)}</span></i>`).join(''):'<div class="admin-empty compact"><strong>아직 집계할 데이터가 없습니다.</strong></div>';$('dashboardSalesSummary').textContent=`최근 7일 총매출 ${MomoAdmin.formatMoney(sales.total)} · 주문 ${sales.count}건`;
  const activities=(MomoAdminActivity?.getLogs()||[]).slice(0,6);$('activityList').innerHTML=activities.length?activities.map(log=>`<li><strong>${log.description||'운영 처리'}</strong><time>${MomoAdmin.relativeTime(log.createdAt)} · ${log.adminName||'관리자'}</time></li>`).join(''):'<li class="empty-admin">최근 관리자 활동이 없습니다.</li>';
  const best=A.menus().slice(0,5);if(!best.length)MomoAdmin.empty($('bestMenus'),'판매 데이터가 없습니다.');else $('bestMenus').innerHTML=`<div class="best-list">${best.map((m,i)=>`<div class="best-item"><span>${i+1}</span><img src="${m.image?('/'+String(m.image).replace(/^\.\.\//,'').replace(/^\//,'')):'/assets/images/momo-face-cute.png'}" alt=""><div><strong>${m.name}</strong><small>${MomoAdmin.formatMoney(m.sales)}</small></div><b>${m.quantity}개</b></div>`).join('')}</div>`;
  const coupon=A.coupons(),point=A.points();$('dashboardRewardStats').innerHTML=`<article><strong>${coupon.available}</strong><span>사용 가능 쿠폰</span></article><article><strong>${coupon.used}</strong><span>사용 완료</span></article><article><strong>${MomoAdmin.formatPoint(point.earned)}</strong><span>누적 적립</span></article><article><strong>${MomoAdmin.formatPoint(point.used)}</strong><span>사용·차감</span></article>`;$('dashboardRewardRecent').innerHTML='<p class="chart-summary">세부 지급·회수 이력은 리워드 관리에서 확인할 수 있습니다.</p>';
})();
