(() => {
  'use strict';
  if(!window.MomoAdmin||!window.MomoAdminSettings)return;
  const form=document.getElementById('settingsForm'),notice=document.getElementById('settingsNotice'),textarea=form.elements.noticeMessage,button=form.querySelector('[type=submit]');
  const names=['storeOpen','orderEnabled','pickupEnabled','maintenanceMode','heroBannerEnabled','seasonMenuEnabled','eventSectionEnabled','appPromotionEnabled'];
  function updatePreview(){document.getElementById('noticeCount').textContent=String(textarea.value.length);document.getElementById('noticePreview').textContent=textarea.value.trim()||'등록된 운영 공지가 없습니다.'}
  function updateState(settings){const text=settings.maintenanceMode?'사이트 점검 중':settings.orderEnabled===false?'주문 일시 중지':settings.storeOpen?'정상 영업 중':'영업 종료',dot=document.getElementById('settingsStateDot');document.getElementById('settingsStateText').textContent=text;dot.style.background=settings.maintenanceMode||settings.orderEnabled===false?'#b56f61':settings.storeOpen?'#80a183':'#a49388'}
  function load(){const settings=MomoAdminSettings.get();names.forEach(name=>form.elements[name].checked=Boolean(settings[name]));form.elements.open.value=settings.businessHours?.open||'09:00';form.elements.close.value=settings.businessHours?.close||'22:00';form.elements.lastOrderTime.value=settings.lastOrderTime||'21:30';textarea.value=settings.noticeMessage||'';updatePreview();updateState(settings)}
  form.addEventListener('input',()=>{updatePreview();notice.textContent='저장되지 않은 변경 사항이 있습니다.'});
  form.addEventListener('submit',async event=>{event.preventDefault();if(!form.elements.open.value||!form.elements.close.value||!form.elements.lastOrderTime.value){notice.textContent='영업시간과 라스트 오더를 모두 입력해 주세요.';MomoAdmin.toast(notice.textContent,'error');return}if(!await MomoAdmin.confirm('고객 화면과 주문 운영 상태에 즉시 반영됩니다.','운영 설정을 변경할까요?'))return;button.disabled=true;try{const value={storeOpen:form.elements.storeOpen.checked,businessHours:{open:form.elements.open.value,close:form.elements.close.value},lastOrderTime:form.elements.lastOrderTime.value,orderEnabled:form.elements.orderEnabled.checked,pickupEnabled:form.elements.pickupEnabled.checked,maintenanceMode:form.elements.maintenanceMode.checked,heroBannerEnabled:form.elements.heroBannerEnabled.checked,seasonMenuEnabled:form.elements.seasonMenuEnabled.checked,eventSectionEnabled:form.elements.eventSectionEnabled.checked,appPromotionEnabled:form.elements.appPromotionEnabled.checked,noticeMessage:textarea.value.trim()},saved=MomoAdminSettings.save(value,MomoAdmin.user);updateState(saved);notice.textContent='운영 설정이 저장되어 고객 화면에 반영되었습니다.';MomoAdmin.toast('운영 설정을 저장했습니다.');window.dispatchEvent(new CustomEvent('momo-admin-data-changed'))}catch(error){notice.textContent=error.message||'설정을 저장하지 못했습니다.';MomoAdmin.toast(notice.textContent,'error')}finally{button.disabled=false}});load();
})();
